import { PokemonType } from '../../domain/schemas/pokemon.schema';

export interface TypeStyle {
  ja: string;
  en: string;
  bg: string;
  text: string;
  border: string;
  glow: string;
  gradient: string;
}

export const TYPE_STYLES: Record<PokemonType, TypeStyle> = {
  normal: {
    ja: 'ノーマル',
    en: 'Normal',
    bg: 'bg-stone-500',
    text: 'text-stone-100',
    border: 'border-stone-400',
    glow: 'shadow-stone-500/30',
    gradient: 'from-stone-600 to-stone-800',
  },
  fire: {
    ja: 'ほのお',
    en: 'Fire',
    bg: 'bg-orange-500',
    text: 'text-white',
    border: 'border-orange-400',
    glow: 'shadow-orange-500/40',
    gradient: 'from-orange-500 to-red-600',
  },
  water: {
    ja: 'みず',
    en: 'Water',
    bg: 'bg-blue-500',
    text: 'text-white',
    border: 'border-blue-400',
    glow: 'shadow-blue-500/40',
    gradient: 'from-blue-500 to-cyan-600',
  },
  grass: {
    ja: 'くさ',
    en: 'Grass',
    bg: 'bg-emerald-500',
    text: 'text-white',
    border: 'border-emerald-400',
    glow: 'shadow-emerald-500/40',
    gradient: 'from-emerald-500 to-green-600',
  },
  electric: {
    ja: 'でんき',
    en: 'Electric',
    bg: 'bg-amber-400',
    text: 'text-stone-900',
    border: 'border-amber-300',
    glow: 'shadow-amber-400/50',
    gradient: 'from-amber-400 to-yellow-500',
  },
  ice: {
    ja: 'こおり',
    en: 'Ice',
    bg: 'bg-cyan-400',
    text: 'text-cyan-950',
    border: 'border-cyan-300',
    glow: 'shadow-cyan-400/40',
    gradient: 'from-cyan-400 to-sky-500',
  },
  fighting: {
    ja: 'かくとう',
    en: 'Fighting',
    bg: 'bg-red-700',
    text: 'text-white',
    border: 'border-red-500',
    glow: 'shadow-red-700/40',
    gradient: 'from-red-600 to-amber-700',
  },
  poison: {
    ja: 'どく',
    en: 'Poison',
    bg: 'bg-purple-600',
    text: 'text-white',
    border: 'border-purple-400',
    glow: 'shadow-purple-600/40',
    gradient: 'from-purple-600 to-fuchsia-700',
  },
  ground: {
    ja: 'じめん',
    en: 'Ground',
    bg: 'bg-amber-700',
    text: 'text-amber-100',
    border: 'border-amber-600',
    glow: 'shadow-amber-700/40',
    gradient: 'from-amber-600 to-yellow-800',
  },
  flying: {
    ja: 'ひこう',
    en: 'Flying',
    bg: 'bg-indigo-400',
    text: 'text-white',
    border: 'border-indigo-300',
    glow: 'shadow-indigo-400/40',
    gradient: 'from-indigo-400 to-sky-500',
  },
  psychic: {
    ja: 'エスパー',
    en: 'Psychic',
    bg: 'bg-pink-500',
    text: 'text-white',
    border: 'border-pink-400',
    glow: 'shadow-pink-500/40',
    gradient: 'from-pink-500 to-rose-600',
  },
  bug: {
    ja: 'むし',
    en: 'Bug',
    bg: 'bg-lime-600',
    text: 'text-white',
    border: 'border-lime-400',
    glow: 'shadow-lime-600/40',
    gradient: 'from-lime-600 to-emerald-700',
  },
  rock: {
    ja: 'いわ',
    en: 'Rock',
    bg: 'bg-yellow-700',
    text: 'text-yellow-100',
    border: 'border-yellow-600',
    glow: 'shadow-yellow-700/40',
    gradient: 'from-yellow-700 to-amber-900',
  },
  ghost: {
    ja: 'ゴースト',
    en: 'Ghost',
    bg: 'bg-violet-700',
    text: 'text-violet-100',
    border: 'border-violet-500',
    glow: 'shadow-violet-700/40',
    gradient: 'from-violet-700 to-purple-900',
  },
  dragon: {
    ja: 'ドラゴン',
    en: 'Dragon',
    bg: 'bg-indigo-700',
    text: 'text-white',
    border: 'border-indigo-500',
    glow: 'shadow-indigo-700/50',
    gradient: 'from-indigo-700 to-violet-800',
  },
  dark: {
    ja: 'あく',
    en: 'Dark',
    bg: 'bg-slate-800',
    text: 'text-slate-100',
    border: 'border-slate-600',
    glow: 'shadow-slate-800/40',
    gradient: 'from-slate-800 to-zinc-950',
  },
  steel: {
    ja: 'はがね',
    en: 'Steel',
    bg: 'bg-slate-400',
    text: 'text-slate-900',
    border: 'border-slate-300',
    glow: 'shadow-slate-400/40',
    gradient: 'from-slate-400 to-zinc-500',
  },
  fairy: {
    ja: 'フェアリー',
    en: 'Fairy',
    bg: 'bg-pink-400',
    text: 'text-pink-950',
    border: 'border-pink-300',
    glow: 'shadow-pink-400/40',
    gradient: 'from-pink-400 to-fuchsia-500',
  },
};
